### ISSUE TITLE
temperature read bug

### ISSUE THREAD

**Issue by Dracanrage** [pschatzmann/pico-arduino#16]
The pico onboard temperature sensor reading is well when the program is flashed in the first time, but when the pico rebooted, it's value turn to be wrong.
For example, the temperature is 26°C, when it rebooted, it will be 406°C.
Seems weird, I tried many ways to figure out its reason but no result.
Is it just a problem only I encountered?

**Comment by pschatzmann** [comment]
I double checked your statement with my temperature-sensor example and could not reproduce the issue.
What do you get when you use this example ?

**Comment by Dracanrage** [comment]
> I double checked your statement with my temperature-sensor example and could not reproduce the issue.
> What do you get when you use this example ?

Like this:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/30333935/113829169-c1bb0280-97b7-11eb-9f5a-526739507bb7.png">
As I get before.

**Comment by pschatzmann** [comment]
The latest correction should resolve this issue. It seems that a reset via the RUN pin is not resetting all the memory like on a proper restart

**Comment by Dracanrage** [comment]
Yes, it works!
Thanks!
