### ISSUE TITLE
How to compile LiquidCrystal_I2C ?

### ISSUE THREAD

**Issue by omikron88** [pschatzmann/pico-arduino#5]
Hello,
I just tried to add LiquidCrystal_I2C to my pico-arduino test project. It ended with some symbol definition errors. But maybe I made something wrong. May you try to make the simple LiquidCrystal_I2C project, please?

**Comment by pschatzmann** [comment]
You are right, it seems that some includes have been missing. I committed some corrections and you can find the example which is compiling now at https://github.com/pschatzmann/pico-arduino/tree/main/sandbox/LiquidCrystal_I2C

**Comment by omikron88** [comment]
I cannot compile my project with SdFat and LiquidCrystal_I2C libraries placed in subdirs.
what am I doing wrong?
the Cmake script is in attachment.
[CMakeLists.txt](https://github.com/pschatzmann/pico-arduino/files/6183994/CMakeLists.txt)

**Comment by pschatzmann** [comment]
What errors are you getting and when ?
By just browsing thru it you should maybe
- remove the file(COPY - which does not make any sense in your case
- replace the CMAKE_SOURCE_DIR with CMAKE_CURRENT_SOURCE_DIR 
but I dont think this is the issue....

p.s. Both cmake and make have some trace and debug options....

**Comment by omikron88** [comment]
> What errors are you getting and when ?
> By just browsing thru it you should maybe

During make

[  9%] Building CXX object CMakeFiles/recorder.dir/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp.obj
In file included from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:3:
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp: In member function 'virtual size_t LiquidCrystal_I2C::write(uint8_t)':
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.h:53:12: warning: 'B00000001' is deprecated: use 0b00000001 instead [-Wdeprecated-declarations]
   53 | #define Rs B00000001  // Register select bit
      |            ^~~~~~~~~
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:11:14: note: in expansion of macro 'Rs'
   11 |  send(value, Rs);
      |              ^~
In file included from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-API/api/ArduinoAPI.h:26,
                 from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-Pico/Arduino.h:17,
                 from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:7:
/home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-API/api/Binary.h:53:3: note: declared here
   53 |   B00000001 DEPRECATED(0b00000001) = 1,
      |   ^~~~~~~~~
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp: In member function 'void LiquidCrystal_I2C::init_priv()':
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:61:13: error: call of overloaded 'begin()' is ambiguous
   61 |  Wire.begin();
      |             ^
In file included from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-Pico/Wire.h:3,
                 from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.h:7,
                 from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:3:
/home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-Pico/PicoHardwareI2C.h:36:20: note: candidate: 'virtual void PicoHardwareI2C::begin()'
   36 |       virtual void begin() {
      |                    ^~~~~
/home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-Pico/PicoHardwareI2C.h:46:12: note: candidate: 'void PicoHardwareI2C::begin(int, int)'
   46 |       void begin(int sdaPin=-1, int sclPin=-1) {
      |            ^~~~~
In file included from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:3:
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp: In member function 'void LiquidCrystal_I2C::pulseEnable(uint8_t)':
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.h:51:12: warning: 'B00000100' is deprecated: use 0b00000100 instead [-Wdeprecated-declarations]
   51 | #define En B00000100  // Enable bit
      |            ^~~~~~~~~
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:259:24: note: in expansion of macro 'En'
  259 |  expanderWrite(_data | En); // En high
      |                        ^~
In file included from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-API/api/ArduinoAPI.h:26,
                 from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-Pico/Arduino.h:17,
                 from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:7:
/home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-API/api/Binary.h:73:3: note: declared here
   73 |   B00000100 DEPRECATED(0b00000100) = 4,
      |   ^~~~~~~~~
In file included from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:3:
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.h:51:12: warning: 'B00000100' is deprecated: use 0b00000100 instead [-Wdeprecated-declarations]
   51 | #define En B00000100  // Enable bit
      |            ^~~~~~~~~
/home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:262:25: note: in expansion of macro 'En'
  262 |  expanderWrite(_data & ~En); // En low
      |                         ^~
In file included from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-API/api/ArduinoAPI.h:26,
                 from /home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-Pico/Arduino.h:17,
                 from /home/user/Plocha/x/pico/Recorder/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp:7:
/home/user/Plocha/x/pico/pico-arduino/Arduino/ArduinoCore-API/api/Binary.h:73:3: note: declared here
   73 |   B00000100 DEPRECATED(0b00000100) = 4,
      |   ^~~~~~~~~
make[2]: *** [CMakeFiles/recorder.dir/build.make:76: CMakeFiles/recorder.dir/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp.obj] Chyba 1
make[1]: *** [CMakeFiles/Makefile2:1496: CMakeFiles/recorder.dir/all] Chyba 2
make: *** [Makefile:84: all] Chyba 2

**Comment by pschatzmann** [comment]
I think you have some old version with some bugs. Try to pull the latest version
